//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace CpsServicesTest.CPA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CPASoap", Namespace="http://tempuri.org/")]
    public partial class CPA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCPAByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCPAByNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdProvinciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdLocalidadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CPA() {
            this.Url = global::CpsServicesTest.Properties.Settings.Default.CpsServicesTest_CPA_CPA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCPAByIdCompletedEventHandler GetCPAByIdCompleted;
        
        /// <remarks/>
        public event GetCPAByNombreCompletedEventHandler GetCPAByNombreCompleted;
        
        /// <remarks/>
        public event GetIdProvinciaCompletedEventHandler GetIdProvinciaCompleted;
        
        /// <remarks/>
        public event GetIdLocalidadCompletedEventHandler GetIdLocalidadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCPAById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCPAById(string idProvincia, int idLocalidad, string calle, string altura) {
            object[] results = this.Invoke("GetCPAById", new object[] {
                        idProvincia,
                        idLocalidad,
                        calle,
                        altura});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCPAByIdAsync(string idProvincia, int idLocalidad, string calle, string altura) {
            this.GetCPAByIdAsync(idProvincia, idLocalidad, calle, altura, null);
        }
        
        /// <remarks/>
        public void GetCPAByIdAsync(string idProvincia, int idLocalidad, string calle, string altura, object userState) {
            if ((this.GetCPAByIdOperationCompleted == null)) {
                this.GetCPAByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCPAByIdOperationCompleted);
            }
            this.InvokeAsync("GetCPAById", new object[] {
                        idProvincia,
                        idLocalidad,
                        calle,
                        altura}, this.GetCPAByIdOperationCompleted, userState);
        }
        
        private void OnGetCPAByIdOperationCompleted(object arg) {
            if ((this.GetCPAByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCPAByIdCompleted(this, new GetCPAByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCPAByNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCPAByNombre(string idProvincia, string nombreLocalidad, string calle, string altura) {
            object[] results = this.Invoke("GetCPAByNombre", new object[] {
                        idProvincia,
                        nombreLocalidad,
                        calle,
                        altura});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCPAByNombreAsync(string idProvincia, string nombreLocalidad, string calle, string altura) {
            this.GetCPAByNombreAsync(idProvincia, nombreLocalidad, calle, altura, null);
        }
        
        /// <remarks/>
        public void GetCPAByNombreAsync(string idProvincia, string nombreLocalidad, string calle, string altura, object userState) {
            if ((this.GetCPAByNombreOperationCompleted == null)) {
                this.GetCPAByNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCPAByNombreOperationCompleted);
            }
            this.InvokeAsync("GetCPAByNombre", new object[] {
                        idProvincia,
                        nombreLocalidad,
                        calle,
                        altura}, this.GetCPAByNombreOperationCompleted, userState);
        }
        
        private void OnGetCPAByNombreOperationCompleted(object arg) {
            if ((this.GetCPAByNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCPAByNombreCompleted(this, new GetCPAByNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIdProvincia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetIdProvincia(string nombreProvincia) {
            object[] results = this.Invoke("GetIdProvincia", new object[] {
                        nombreProvincia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetIdProvinciaAsync(string nombreProvincia) {
            this.GetIdProvinciaAsync(nombreProvincia, null);
        }
        
        /// <remarks/>
        public void GetIdProvinciaAsync(string nombreProvincia, object userState) {
            if ((this.GetIdProvinciaOperationCompleted == null)) {
                this.GetIdProvinciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdProvinciaOperationCompleted);
            }
            this.InvokeAsync("GetIdProvincia", new object[] {
                        nombreProvincia}, this.GetIdProvinciaOperationCompleted, userState);
        }
        
        private void OnGetIdProvinciaOperationCompleted(object arg) {
            if ((this.GetIdProvinciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdProvinciaCompleted(this, new GetIdProvinciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIdLocalidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GetIdLocalidad(string idProvincia, string nombreLocalidad) {
            object[] results = this.Invoke("GetIdLocalidad", new object[] {
                        idProvincia,
                        nombreLocalidad});
            return ((System.Nullable<int>)(results[0]));
        }
        
        /// <remarks/>
        public void GetIdLocalidadAsync(string idProvincia, string nombreLocalidad) {
            this.GetIdLocalidadAsync(idProvincia, nombreLocalidad, null);
        }
        
        /// <remarks/>
        public void GetIdLocalidadAsync(string idProvincia, string nombreLocalidad, object userState) {
            if ((this.GetIdLocalidadOperationCompleted == null)) {
                this.GetIdLocalidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdLocalidadOperationCompleted);
            }
            this.InvokeAsync("GetIdLocalidad", new object[] {
                        idProvincia,
                        nombreLocalidad}, this.GetIdLocalidadOperationCompleted, userState);
        }
        
        private void OnGetIdLocalidadOperationCompleted(object arg) {
            if ((this.GetIdLocalidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdLocalidadCompleted(this, new GetIdLocalidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCPAByIdCompletedEventHandler(object sender, GetCPAByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCPAByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCPAByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCPAByNombreCompletedEventHandler(object sender, GetCPAByNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCPAByNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCPAByNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetIdProvinciaCompletedEventHandler(object sender, GetIdProvinciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdProvinciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdProvinciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetIdLocalidadCompletedEventHandler(object sender, GetIdLocalidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdLocalidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdLocalidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<int> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<int>)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591